spring:
  rabbitmq:
    exchanges: internal.exchange
    routing-keys: internal.notification.routing-key
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: notification.queue

server:
  port: 8089
